### ISSUE TITLE
Final model launch Engineering TODO tracker

### ISSUE THREAD

**Issue by stas00** [bigscience-workshop/Megatron-DeepSpeed#252]
## This is the tracker for the final launch

**Please edit directly** (contact me on slack if you need write access)

-------------------

General TODO:

- [x] hparam config - happening right now (Iz is working on it)
- [x] waiting for BF16 updates from Deepspeed
- [ ] Hanging issue - have an adequate workaround - but continuing to debug it
- [x] Setup a hub repo to tb/log files once we decided on the model size

------------------

Pre-main run test:
- [x] run a small (1.3B?) model training in fp16 and bf16 each for may be a day and compare the loss is close enough

-------------------

Sat Feb26 morning PST:
- [x] update to the latest pt-1.11-rc2 which should be uploaded around 4am
```
pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/test/cu115/torch_test.html -U
```
then rebuild `apex` and `deepspeed`
test run

-------------------

- [x] could probably update to the final pt-1.11 when it's released in early March.

**Comment by stas00** [comment]
all done.
